---
# tasks file for userquota
- name: Log User created event
  debug:
    msg: "User created: {{ _user_openshift_io_user.metadata.name }} -> Setting up ClusterResourceQuota"

- name: Retrieve available UserQuotas
  k8s_facts:
    api_version: gpte.opentlc.com/v1alpha1
    kind: UserQuota
    name: default
    namespace: gpte-operators
  register:
    user_quota

- name: Print some debug information 
  vars: 
    msg: |
        Module Variables ("vars"):
        --------------------------------
        {{ vars | to_nice_json }} 
 
        Environment Variables ("environment"):
        --------------------------------
        {{ environment | to_nice_json }} 
 
        GROUP NAMES Variables ("group_names"):
        --------------------------------
        {{ group_names | to_nice_json }}
 
        GROUPS Variables ("groups"):
        --------------------------------
        {{ groups | to_nice_json }}
 
        HOST Variables ("hostvars"):
        --------------------------------
        {{ hostvars | to_nice_json }} 
  debug: 
    msg: "{{ msg.split('\n') }}"       
  tags: debug_info

# User Quota found - add it to the User
- name: Add ClusterResourceQuota to User
  when:
  - user_quota.resources | length > 0
  block:
  - name: Print Quota for debug
    debug:
      msg: "Found Quota:\n{{ user_quota.resources[0].spec.quota }}"

  - name: Create ClusterResourceQuota
    k8s:
      state: present
      definition: "{{ lookup('template', './templates/cluster_resource_quota.j2') }}"

        # "    \"localhost\": {",
        # "        \"_user_openshift_io_user\": {",
        # "            \"apiVersion\": \"user.openshift.io/v1\",",
        # "            \"fullName\": \"wolfgang kulhanek\",",
        # "            \"groups\": null,",
        # "            \"identities\": [",
        # "                \"ldapidp:uid=wkulhane-redhat.com,cn=users,cn=accounts,dc=opentlc,dc=com\"",
        # "            ],",
        # "            \"kind\": \"User\",",
        # "            \"metadata\": {",
        # "                \"creationTimestamp\": \"2019-04-19T19:27:26Z\",",
        # "                \"name\": \"wkulhane-redhat.com\",",
        # "                \"resourceVersion\": \"1092308\",",
        # "                \"selfLink\": \"/apis/user.openshift.io/v1/users/wkulhane-redhat.com\",",
        # "                \"uid\": \"2a0148cd-62d9-11e9-ae1e-0a580a800021\"",
        # "            },",
        # "            \"spec\": {}",
        # "        },",

        # "        \"user_quota\": {",
        # "            \"changed\": false,",
        # "            \"failed\": false,",
        # "            \"resources\": []",
        # "        }",

        #         "        \"user_quota\": {",
        # "            \"changed\": false,",
        # "            \"failed\": false,",
        # "            \"resources\": [",
        # "                {",
        # "                    \"apiVersion\": \"gpte.opentlc.com/v1alpha1\",",
        # "                    \"kind\": \"UserQuota\",",
        # "                    \"metadata\": {",
        # "                        \"creationTimestamp\": \"2019-04-19T20:11:04Z\",",
        # "                        \"generation\": 1,",
        # "                        \"name\": \"default\",",
        # "                        \"namespace\": \"gpte-operators\",",
        # "                        \"resourceVersion\": \"1110364\",",
        # "                        \"selfLink\": \"/apis/gpte.opentlc.com/v1alpha1/namespaces/gpte-operators/userquota/default\",",
        # "                        \"uid\": \"42c8afe0-62df-11e9-8777-0a45d1c86b4c\"",
        # "                    },",
        # "                    \"spec\": {",
        # "                        \"quota\": {",
          # "                        \"hard\": {",
          # "                            \"configmaps\": \"10\",",
          # "                            \"limits.cpu\": \"10\",",
          # "                            \"limits.memory\": \"20Gi\",",
          # "                            \"persistentvolumeclaims\": \"20\",",
          # "                            \"pods\": \"20\",",
          # "                            \"requests.cpu\": \"5\",",
          # "                            \"requests.memory\": \"6Gi\",",
          # "                            \"requests.storage\": \"50Gi\",",
          # "                            \"secrets\": \"150\",",
          # "                            \"services\": \"30\"",
          # "                        }",
        # "                        }",
        # "                    },",